### PR TITLE
Compress attachment immediately after downloading

### LINKED ISSUE #1106: Compress images on download instead of on load
This is likely due to the attachment metadata being loaded into BB. Not sure why it lags the UI since it should all happen in the background. But maybe this is something we need to do via a dart VM so it doesn't lag the UI thread? Not sure

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

### PR DESCRIPTION
**Pull request by tneotia**
Fixes #1106

### CODE REVIEW

**Review by zlshames — CHANGES_REQUESTED** [review]
Crap, this is my fault originally. But we need to make compressAttachment only handle image file-types, right? Like exclude video (and gifs?). That way it doesn’t try to compress EVERY attachment. Similar to what we do in `setDimensions`. I’m also wondering if we should combine `setDimensions` and `compressAttachment`

**Comment by tneotia** [comment]
Fixed that

**Review by zlshames — CHANGES_REQUESTED** [review]
Sorry to be nitpicky, but I would like to combine them and get rid of setDimensions. Looks like setDimensions uses ImageSizeGetter. If we can remove that dependency and just use FlutternativeImage, that's better imo. We still need to check if it's a GIF, and if so, use the GIF image dimensions call. And if it's a video, use the getVideo dimensions call. But we should essentially combine them imo

**Comment by tneotia** [comment]
Done

**Review by zlshames — CHANGES_REQUESTED** [review]
Hey, so can you call the ImageSizeGetter in 2 cases? 1, in the catch (as you already have it). And 2, if the height/width returned by FlutterNativeImage are 0 (either of them).

So we still need to do the 2nd case. I just want to make sure that we get the size no matter what (to our best ability)

**Comment by tneotia** [comment]
> Hey, so can you call the ImageSizeGetter in 2 cases? 1, in the catch (as you already have it). And 2, if the height/width returned by FlutterNativeImage are 0 (either of them).
> 
> So we still need to do the 2nd case. I just want to make sure that we get the size no matter what (to our best ability)

Done

**Pull request merged**
