### PR TITLE
Zach/nightly

### PR DESCRIPTION
**Pull request by SoPat712**

### CODE REVIEW

**Review by zlshames — COMMENTED** [review]
Was this only a nightly issue?

**Review by zlshames — COMMENTED** [review]
Did the AppBar use the contact's color before? And not just the Theme.of(context).backgroundColor?

**Review by zlshames — COMMENTED** [review]
I'm scared to merge this code here to `messages_view.dart` regarding `Revert MessagesView to working state`. What exactly did you do here? What was the issue and how did you fix it?

**Review by zlshames — CHANGES_REQUESTED** [review]
I wouldn't change this version just yet. Remove this por-favor

**Comment by SoPat712** [comment]
> Was this only a nightly issue (the dupe Smart Reply option)?

it was an issue that came up after you merged nightly with master

**Comment by SoPat712** [comment]
> Did the AppBar use the contact's color before? And not just the Theme.of(context).backgroundColor?

It used the contacts toColorGradient for the appBar, but seeing as you use the message handle or whatever to get the custom color set, I'm not sure how to make the appBar use that color. Either way, it looked weird.

**Comment by SoPat712** [comment]
> I'm scared to merge this code here to `messages_view.dart` regarding `Revert MessagesView to working state`. What exactly did you do here? What was the issue and how did you fix it?

Oh yeah, right I forgot about that. I replaced messages_view.dart with the older nightly messages_view dart instead of the post-merge messages_view.dart. It fixed the scroll to bottom indicator being broken, but it might have reverted any changes you made on beta to messages_view.dart

**Comment by SoPat712** [comment]
> > I'm scared to merge this code here to `messages_view.dart` regarding `Revert MessagesView to working state`. What exactly did you do here? What was the issue and how did you fix it?
> 
> Oh yeah, right I forgot about that. I replaced messages_view.dart with the older nightly messages_view dart instead of the post-merge messages_view.dart. It fixed the scroll to bottom indicator being broken, but it might have reverted any changes you made on beta to messages_view.dart

should I just go back to the merged messages_view, and just manually fix the scroll to bottom issues or whatever else came up?

**Pull request merged**
