### PR TITLE
Potentially fix sharing to a chat that is already open

### LINKED ISSUE #1275: Images shared to a chat that is already opened, do not get added to the share preview
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

### PR DESCRIPTION
**Pull request by tneotia**
Fixes #1275, couldn't test bc my share targets wouldn't update

### CODE REVIEW

**Comment by zlshames** [comment]
> Fixes #1275, couldn't test bc my share targets wouldn't update

FYI, I don’t think this is unique to share targets. I think the issue happens when sharing normally as well

**Comment by zlshames** [comment]
Merging this, but leaving the ticket open until we confirm the fix

**Comment by tneotia** [comment]
> > Fixes #1275, couldn't test bc my share targets wouldn't update
> 
> FYI, I don’t think this is unique to share targets. I think the issue happens when sharing normally as well

When we share normally it opens the new chat creator - if you're in a chat it shouldn't affect anything, at least it hasn't for me.

**Comment by jjoelj** [comment]
can confirm doesn't work

**Comment by tneotia** [comment]
Rip

**Pull request merged**
