### PR TITLE
Fix colorful avatars not updating after toggled

### LINKED ISSUE #1108: colorful avatars don't take effect immediately on the conversation list after enabling the setting
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-bugs`.

### PR DESCRIPTION
**Pull request by tneotia**
Fixes #1108

### CODE REVIEW

**Review by zlshames — APPROVED** [review]
I love that GetX allows us to better react to these config changes. It was a pain dealing with it before without a controller/state management system

**Comment by zlshames** [comment]
We may have to do the same for the colorful bubbles option

**Comment by tneotia** [comment]
Nah that works fine because the colorful bubbles state will never be modified while that screen is open. Colorful avatars will be since the conversation list is active while in settings.

**Comment by zlshames** [comment]
> Nah that works fine because the colorful bubbles state will never be modified while that screen is open. Colorful avatars will be since the conversation list is active while in settings.

There is a super old bug that Monica originally ran into where if you turn on colorful bubbles, then go into a chat, the colors of the bubbles changed, but any new messages that come in will be the old color. 

Maybe this has been fixed throughout time and all the changes 🤷🏽‍♂️

**Comment by tneotia** [comment]
Ah okay I haven't seen this personally but it might be a thing 🤷‍♂️

**Pull request merged**
