### PR TITLE
[WIP] Better Pinned Chats — Like those on iOS 14

### PR DESCRIPTION
**Pull request by AidanLovelace**
Can't post screenshots for privacy reasons :(.

Moved pinned chats to the top in a 3 by X grid like Apple added with iOS 14.

THIS IS STILL WORK IN PROGRESS

### CODE REVIEW

**Comment by zlshames** [comment]
Awesome work @AidanLovelace! Is this toggleable? If not, can you add a setting for it and have it disabled by default? To do that, you'll need to edit the following files:

* settings.dart -> there are 3 places you need to add the new config item. You'll see other similar times there
* theme_panel.dart -> where you add the config switch
* conversation_list.dart -> add the toggle using SettingsManager().settings.yournewconfigitem

**Comment by SoPat712** [comment]
Yeah I kinda wanna see a screenshot too! If you have a Samsung device, you can edit the screenshot and scribble out any names or private text messages.

**Comment by AidanLovelace** [comment]
image
Here's a good screenshot.

**Comment by SoPat712** [comment]
Looks great! Why is that in a 3x2 grid instead of a 2x2 grid?

**Comment by AidanLovelace** [comment]
It's a 3xWhatever grid, like Apple does is on iOS.

**Comment by SoPat712** [comment]
Well we don't really need to follow all their decisions to a T, but whatever, no big deal. Great work either way, it looks amazing!

**Comment by zlshames** [comment]
What's the status of this @AidanLovelace ?

**Comment by SoPat712** [comment]
I thought completed?

**Comment by zlshames** [comment]
@AidanLovelace Sorry to ping again, but did you finish this? If so, can you mark it not as [WIP]?

**Pull request closed without merging**
